### ISSUE TITLE
Strategy loses the params on its way

### ISSUE THREAD

**Issue by devel-pa** [feathersjs/authentication-jwt#36]
Hi,
I had an issue with chaining the hooks, standard stuff (authenticate, restrictToOwner) and I realized that the params not arriving to the next hook from time to time.

The next line:

https://github.com/feathersjs/feathers-authentication-jwt/blob/master/src/verifier.js#L30

Shouldn't be like
```
this.service.get(id, req.params).then(function (entity) {
```

At least for me fixed the issue (after hours of debugging).

Thanks,
Paul

**Comment by devel-pa** [comment]
Looks like didn't worked as expected even for me :)
Instead this works:

```
    let {provider, ...params} = req.params;
    this.service.get(id, params).then(function (entity) {
```

**Comment by daffl** [comment]
This is intended. If you need the parameters you can implement a [custom verifier](https://docs.feathersjs.com/api/authentication/jwt.html#customizing-the-verifier).
