### ISSUE TITLE
document `expiresIn`

### ISSUE THREAD

**Issue by arve0** [feathersjs/authentication-jwt#39]
Hi!
As far as I can see, `expiresIn` is not a passport-jwt option, but a [jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) option. If that is correct, maybe we could document that it uses [zeit/ms](https://github.com/zeit/ms)?

**Comment by daffl** [comment]
The options for creating a JWT are documented in https://docs.feathersjs.com/api/authentication/server.html#options
