### ISSUE TITLE
JWT verifier: do not return 404 error on not found identity

### ISSUE THREAD

**Issue by mgesmundo** [feathersjs/authentication-jwt#63]
Hi there,

I think that the verifier should not return the error on 404 finding a missing identity. The use case:

1. get a valid token with a valid user
2. get a request for an endpoint with this token -> ok
3. delete the user
4. make a new request with the same token -> 404

I think that the verifier should return 401 with Unknown user.
It is a wrong though?
All the best!

**Comment by daffl** [comment]
If that is the desired behaviour for your application you can [customize the JWT](https://docs.feathersjs.com/api/authentication/jwt.html#verifier) verifier.

**Comment by mgesmundo** [comment]
Yes of course I customized the verifier. My thought was only on what was the best error message for the use case: maybe they are both correct.
Thank you for your awesome framework!
